### PR TITLE
Support for username and password outside settings.xml

### PR DESCRIPTION
**Pull request by pettersolberg88**
Hi.

I added support for username and password as an parameter instead of settings.xml
It will be fine if you also can release a new version to maven

### CODE REVIEW

**Comment by sixro** [comment]
Hi @pettersolberg88 and thank you for this pull request.
Just a question: is there any issue with the serverId? I found it the "preferred way" 'cause having the username/password in the pom.xml could lead to security issues...
Cheers
  6ro

**Comment by pettersolberg88** [comment]
I agree with you. ServerId in settings.xml is the prefered way i comparison to have it directly in the pom. If you have the password in cleartext in the pom it will be an securityissue. Because the pom will be uploaded when releaseing the maven artifact.
But if you use an property reference instead it will not be available in the uploaded pom. For example
<password>${passwordProperty}</password>
And run maven with -DpasswordProperty=MyPassword
There is no issue (that I can see)

**Comment by pettersolberg88** [comment]
@sixro Do you approve my pull request? 
The feature is good for projects built on shared build servers where access to settings.xml is restriced.

**Comment by sixro** [comment]
Sure. I'm just in holiday and I forgot where I put the pwd of sonatype
account :D
I'll approve it in a couple of days
Cheers
  R

Il 06/gen/2017 11:27, "pettersolberg88" <notifications@github.com> ha
scritto:

**Comment by sixro** [comment]
Hi @pettersolberg88, would you mind adding your name/info/whatever in the contributor list?
Cheers

**Comment by pettersolberg88** [comment]
@sixro I have now added myself to the contributer list

/Petter

**Pull request merged**
